const fs = require('fs').promises;
const path = require('path');
const logger = require('../logging/logger');
const { getLlmProvider } = require('../llm');
const { saveArtifact, Artifact } = require('../models/artifact');
const { getEvidence, saveEvidence } = require('../models/evidence');
const settingsService = require('../services/settingsService');
const { convertAudioToMp3, splitAudioFile } = require('../utils/audioChunker');

const transcribeEvidence = async (job) => {
  const { evidenceId, filename, originalName, processName } = job.data;
  logger.info({ jobId: job.id, evidenceId }, 'Starting audio transcription');

  let baseName = processName || (originalName ? originalName.replace(/\.[^/.]+$/, '') : filename.replace(/\.[^/.]+$/, ''));
  const normalizedName = baseName
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');

  let chunkPaths = [];
  let persistentAudioPath = null;

  try {
    const evidence = await getEvidence(evidenceId);
    if (!evidence) {
      throw new Error(`Evidence not found: ${evidenceId}`);
    }

    const { provider, model, apiKey, baseUrl, maxFileSizeMB } = settingsService.getTranscriptionConfig();
    const llm = getLlmProvider({
      provider,
      model,
      apiKey,
      baseURL: baseUrl,
    });

    // Check if provider supports transcribe
    if (typeof llm.transcribe !== 'function') {
      throw new Error(`Provider ${provider} does not support transcription`);
    }

    const outputDir = path.dirname(evidence.path);
    const normalizedAudioFilename = `${path.basename(evidence.path, path.extname(evidence.path))}-normalized.mp3`;
    persistentAudioPath = path.join(outputDir, normalizedAudioFilename);

    try {
      await fs.access(persistentAudioPath);
      logger.info({ jobId: job.id, evidenceId, persistentAudioPath }, 'Reusing existing normalized audio file');
    } catch {
      await convertAudioToMp3(evidence.path, persistentAudioPath);
      logger.info({ jobId: job.id, evidenceId, persistentAudioPath }, 'Created normalized audio file');
    }

    evidence.metadata = {
      ...(evidence.metadata || {}),
      transcription: {
        ...((evidence.metadata || {}).transcription || {}),
        convertedAudioPath: persistentAudioPath,
        convertedAudioFilename: normalizedAudioFilename,
        convertedAudioMimeType: 'audio/mpeg',
        convertedAudioBitrate: '128k',
        convertedAudioCreatedAt: new Date().toISOString(),
      },
    };
    await saveEvidence(evidence);

    chunkPaths = await splitAudioFile(persistentAudioPath, maxFileSizeMB, outputDir);

    logger.info({ jobId: job.id, chunks: chunkPaths.length }, 'Transcribing audio chunks in sequence');

    // We transcribe in sequence to not overwhelm rate limits and strictly preserve order
    let finalTranscript = '';
    for (let i = 0; i < chunkPaths.length; i++) {
      logger.info({ chunk: i + 1, total: chunkPaths.length }, 'Transcribing chunk');
      // Language is auto-detected by default for Whisper, or could be passed from frontend
      const transcriptSegment = await llm.transcribe(chunkPaths[i], job.data.language);
      finalTranscript += transcriptSegment + ' ';
    }

    finalTranscript = finalTranscript.trim();

    const artifactFilename = `${normalizedName}_transcript.txt`;
    const artifact = new Artifact({
      type: 'transcript',
      content: finalTranscript,
      filename: artifactFilename,
      metadata: {
        sourceEvidenceId: evidenceId,
        jobId: job.id,
        extension: 'txt',
        chunksProcessed: chunkPaths.length,
      },
      user_id: job.user_id,
      workspace_id: job.workspace_id,
      llm_provider: provider,
      llm_model: model,
    });
    await saveArtifact(artifact);

    logger.info(
      {
        event_type: 'artifact_generated',
        artifact_id: artifact.id,
        artifact_type: 'transcript',
        jobId: job.id,
      },
      'Generated transcript artifact',
    );

    return {
      success: true,
      evidenceId,
      artifacts: [{ type: 'transcript', id: artifact.id, format: 'txt' }],
    };
  } catch (err) {
    logger.error({ jobId: job.id, err }, 'Audio transcription failed');
    throw err;
  } finally {
    // Cleanup any temporary chunks generated by splitAudioFile
    const cleanupTargets = chunkPaths.filter((chunkPath) => chunkPath !== persistentAudioPath);
    for (const [chunkIndex, chunkPath] of cleanupTargets.entries()) {
      try {
        await fs.unlink(chunkPath);
      } catch (cleanupErr) {
        logger.warn({ cleanupErr, chunkIndex, chunkPath }, 'Failed to cleanup audio chunk');
      }
    }
  }
};

module.exports = {
  transcribeEvidence,
};
