const catalog = [
  {
    id: 'llama3.2',
    label: 'Llama 3.2',
    description: 'Fast general-purpose local model',
    sizeLabel: '3 GB',
    parameterSize: '3B',
    contextWindow: '128K',
    hardwareRequirements: {
      ram: '8 GB minimum, 16 GB recommended',
      cpu: 'Modern 4-core CPU or better',
      gpu: 'Optional. 6 GB+ VRAM improves response time',
    },
    recommended: true,
  },
  {
    id: 'qwen3.5:4b',
    label: 'Qwen 3.5 4B',
    description: 'Compact reasoning model with strong multilingual and tool-use support',
    sizeLabel: '3.4 GB',
    parameterSize: '4.66B',
    contextWindow: '256K',
    hardwareRequirements: {
      ram: '8 GB minimum, 16 GB recommended',
      cpu: 'Modern 4-core CPU or better',
      gpu: 'Optional. 6 GB+ VRAM improves throughput',
    },
    recommended: true,
  },
  {
    id: 'qwen3.5:9b',
    label: 'Qwen 3.5 9B',
    description: 'Balanced reasoning and structured output with a large context window',
    sizeLabel: '6.6 GB',
    parameterSize: '9B',
    contextWindow: '256K',
    hardwareRequirements: {
      ram: '16 GB minimum, 24 GB recommended',
      cpu: 'Modern 6-core CPU or better',
      gpu: 'Recommended. 8 GB+ VRAM for smoother inference',
    },
    recommended: true,
  },
  {
    id: 'qwen3.5:27b',
    label: 'Qwen 3.5 27B',
    description: 'High-capability long-context model for heavier reasoning and coding work',
    sizeLabel: '17 GB',
    parameterSize: '27B',
    contextWindow: '256K',
    hardwareRequirements: {
      ram: '32 GB minimum, 48 GB recommended',
      cpu: 'Modern 8-core CPU or better',
      gpu: 'Strongly recommended. 24 GB+ VRAM for practical local use',
    },
    recommended: false,
  },
  {
    id: 'glm-4.7-flash',
    label: 'GLM-4.7 Flash',
    description: 'Large-context model optimized for strong reasoning, coding, and agent workflows',
    sizeLabel: '19 GB',
    parameterSize: '30B-A3B MoE',
    contextWindow: '198K',
    hardwareRequirements: {
      ram: '32 GB minimum, 48 GB recommended',
      cpu: 'Modern 8-core CPU or better',
      gpu: 'Strongly recommended. 24 GB+ VRAM for practical inference',
    },
    recommended: false,
  },
  {
    id: 'mistral',
    label: 'Mistral',
    description: 'Balanced reasoning and speed',
    sizeLabel: '4 GB',
    parameterSize: '7B',
    contextWindow: '32K',
    hardwareRequirements: {
      ram: '16 GB minimum, 24 GB recommended',
      cpu: 'Modern 6-core CPU or better',
      gpu: 'Recommended. 8 GB+ VRAM for faster generation',
    },
    recommended: false,
  },
  {
    id: 'phi3.5',
    label: 'Phi-3.5',
    description: 'Smaller model for quick local validation with long-context support',
    sizeLabel: '2.2 GB',
    parameterSize: '3.8B',
    contextWindow: '4K default / 128K capable',
    hardwareRequirements: {
      ram: '8 GB minimum',
      cpu: 'Modern 4-core CPU',
      gpu: 'Optional. Runs well on CPU-only systems',
    },
    recommended: false,
  },
];

module.exports = catalog;
